# Generated by Django 5.0 on 2024-01-02 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.PositiveIntegerField(default=0, verbose_name='余额'),
        ),
        migrations.CreateModel(
            name='AccountRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=0, verbose_name='金额')),
                ('balance', models.PositiveIntegerField(verbose_name='余额')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('account_type', models.BooleanField(choices=[(True, '收入'), (False, '支出')], default=True, verbose_name='账户类型')),
                ('remark', models.CharField(blank=True, max_length=255, null=True, verbose_name='备注')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '账户记录',
                'verbose_name_plural': '账户记录',
                'db_table': 'account_record',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SignInDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='日期')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '签到日期',
                'verbose_name_plural': '签到日期',
                'db_table': 'sign_in_date',
                'ordering': ['-id'],
            },
        ),
    ]
