# Generated by Django 5.0 on 2024-01-03 11:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_balance_accountrecord_signindate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountrecord',
            name='account_type',
        ),
        migrations.AddField(
            model_name='accountrecord',
            name='record_type',
            field=models.BooleanField(choices=[(True, '收入'), (False, '支出')], default=True, verbose_name='记录类型'),
        ),
        migrations.AddField(
            model_name='accountrecord',
            name='reward_type',
            field=models.PositiveSmallIntegerField(choices=[(0, '签到'), (1, '分享'), (2, '充值')], default=1, verbose_name='收支分类'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='RechargeableCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=20, unique=True, verbose_name='卡号')),
                ('amount', models.PositiveIntegerField(default=0, verbose_name='金额')),
                ('is_used', models.BooleanField(default=False, verbose_name='是否已使用')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '充值卡',
                'verbose_name_plural': '充值卡',
                'db_table': 'rechargeable_card',
            },
        ),
    ]
