# Generated by Django 5.0 on 2024-01-03 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_accountrecord_account_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rechargeablecard',
            name='use_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='使用时间'),
        ),
    ]
