# Generated by Django 5.0 on 2024-01-14 18:15

import apps.user.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0004_alter_accountrecord_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountrecord",
            name="reward_type",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "签到"), (1, "分享"), (2, "充值"), (3, "绘图"), (4, "新用户注册")],
                verbose_name="收支分类",
            ),
        ),
        migrations.AlterField(
            model_name="rechargeablecard",
            name="card_number",
            field=models.CharField(
                default=apps.user.models.random_card_number,
                max_length=20,
                unique=True,
                verbose_name="卡号",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.CharField(
                default="https://ai-media.xiazq.com/media/avatar.jpg",
                max_length=255,
                verbose_name="头像",
            ),
        ),
    ]
