# Generated by Django 5.0 on 2024-01-05 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DrawConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.CharField(default='', max_length=255, verbose_name='提示词')),
                ('negative_prompt', models.CharField(default='', max_length=255, verbose_name='负面提示词')),
                ('config', models.JSONField(default=dict, verbose_name='配置')),
                ('width', models.PositiveSmallIntegerField(verbose_name='宽度')),
                ('height', models.PositiveSmallIntegerField(verbose_name='高度')),
                ('seed', models.SmallIntegerField(default=-1, verbose_name='种子')),
            ],
            options={
                'verbose_name': '绘图配置',
                'verbose_name_plural': '绘图配置',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Lora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Lora中文昵称')),
                ('nickname', models.CharField(default='', max_length=100, verbose_name='Lora名称')),
                ('weight', models.FloatField(default=1, verbose_name='权重')),
                ('cover', models.ImageField(default='', upload_to='lora/', verbose_name='封面')),
                ('sort', models.PositiveSmallIntegerField(default=0, help_text='排序', verbose_name='排序')),
            ],
            options={
                'verbose_name': 'Lora模型',
                'verbose_name_plural': 'Lora模型',
                'ordering': ['-sort', '-id'],
            },
        ),
    ]
