# Generated by Django 5.0 on 2024-01-05 20:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Styles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='风格名称')),
                ('style', models.CharField(default='', max_length=255, verbose_name='风格')),
                ('sort', models.PositiveSmallIntegerField(default=0, help_text='排序', verbose_name='排序')),
            ],
            options={
                'verbose_name': '风格',
                'verbose_name_plural': '风格',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='drawconfig',
            name='lora',
            field=models.ManyToManyField(blank=True, to='draw.lora', verbose_name='Lora模型'),
        ),
        migrations.AddField(
            model_name='drawconfig',
            name='sampler_name',
            field=models.CharField(default='', max_length=100, verbose_name='采样器'),
        ),
        migrations.CreateModel(
            name='DrawHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='draw/', verbose_name='图片')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, '进行中'), (1, '成功'), (2, '失败')], default=0, verbose_name='状态')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='draw.drawconfig', verbose_name='配置')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '绘图历史',
                'verbose_name_plural': '绘图历史',
                'ordering': ['-id'],
            },
        ),
    ]
