# Generated by Django 5.0 on 2024-01-12 20:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("draw", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Machines",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(default="", max_length=100, verbose_name="机器名称"),
                ),
                (
                    "agreement",
                    models.BooleanField(
                        choices=[(True, "http"), (False, "https")],
                        default=True,
                        verbose_name="传输协议",
                    ),
                ),
                (
                    "ip",
                    models.CharField(default="", max_length=40, verbose_name="机器IP"),
                ),
                (
                    "post",
                    models.CharField(default="", max_length=10, verbose_name="机器端口"),
                ),
                ("enabled", models.BooleanField(default=True, verbose_name="是否启用")),
            ],
            options={
                "verbose_name": "机器管理",
                "verbose_name_plural": "机器管理",
                "ordering": ["-id"],
            },
        ),
        migrations.AlterModelOptions(
            name="promptassistant",
            options={
                "ordering": ["id"],
                "verbose_name": "提示词助手",
                "verbose_name_plural": "提示词助手",
            },
        ),
        migrations.AddField(
            model_name="drawhistory",
            name="audit",
            field=models.BooleanField(default=False, verbose_name="审核通过"),
        ),
        migrations.AddField(
            model_name="drawhistory",
            name="audit_txt",
            field=models.CharField(default="", max_length=255, verbose_name="审核备注"),
        ),
        migrations.AlterField(
            model_name="userlike",
            name="history",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="history_set",
                to="draw.drawhistory",
                verbose_name="绘图历史",
            ),
        ),
        migrations.CreateModel(
            name="MachineLogs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="使用时间"),
                ),
                (
                    "total_time",
                    models.CharField(default="", max_length=20, verbose_name="耗费时间"),
                ),
                ("remark", models.TextField(default="", verbose_name="备注")),
                (
                    "config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="draw.drawconfig",
                        verbose_name="配置",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
                (
                    "machine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="draw.machines",
                        verbose_name="机器",
                    ),
                ),
            ],
            options={
                "verbose_name": "机器日志",
                "verbose_name_plural": "机器日志",
                "ordering": ["-id"],
            },
        ),
    ]
