# Generated by Django 5.0 on 2024-01-05 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0002_styles_drawconfig_lora_drawconfig_sampler_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lora',
            new_name='Loras',
        ),
    ]
