# Generated by Django 5.0 on 2024-01-05 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0003_rename_lora_loras'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptAssistant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('prompts', models.JSONField(verbose_name='提示词')),
            ],
            options={
                'verbose_name': '提示词助手',
                'verbose_name_plural': '提示词助手',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='RandomPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('prompts', models.JSONField(verbose_name='提示词')),
            ],
            options={
                'verbose_name': '随机提示词',
                'verbose_name_plural': '随机提示词',
                'ordering': ['-id'],
            },
        ),
    ]
