# Generated by Django 5.0 on 2024-01-05 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0004_promptassistant_randomprompt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='styles',
            options={'ordering': ['-sort', '-id'], 'verbose_name': '风格', 'verbose_name_plural': '风格'},
        ),
        migrations.AlterField(
            model_name='promptassistant',
            name='prompts',
            field=models.JSONField(default=dict, verbose_name='提示词'),
        ),
        migrations.AlterField(
            model_name='randomprompt',
            name='prompts',
            field=models.JSONField(default=dict, verbose_name='提示词'),
        ),
    ]
